language: php
php:
  - 5.4
  - 5.5
  - 5.6
sudo: false
cache:
  directories:
    - _vendor
    - $HOME/.composer/cache
install:
  - composer install
script: sh ./_shell/apigen.sh
branches:
  only:
    - gh-pages
notifications:
  email:
    on_success: never
    on_failure: never
